#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'raytrace'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('MAPBASE', 1)
	conf.define('MAPBASE_VSCRIPT',1)

def build(bld):
	source = [
		'raytrace.cpp',
		'trace2.cpp',
		'trace3.cpp',
	]

	includes = [
		'.',
		'../common',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../public/mathlib',
		'../utils/common',
	]	

	defines = []

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'tier3',
		'mathlib',
		'vstdlib',
	]

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

