/*
 * hl2sb_hooks.c - GMod-style engine hook name registry (HL2SB).
 *
 * GMod's lua_shared.dll owns the names of every hook its C++ side can
 * dispatch: game code passes only a small numeric id (client.dll literally
 * does CallWithArgs(0x2e)) and this shared table resolves it to the string.
 * That is why GMod's binaries contain each hook name exactly once.
 *
 * The table below is GMod's own, extracted slot-for-slot from GMod's
 * lua_shared.dll .data (both installed builds, x86 + win64).  Slot order IS
 * the id space: kHookNames[i] has id i.  A reference GMod call
 * CallWithArgs(0x2e) therefore maps to HL2SB_HOOK_HUDITEMPICKEDUP here with
 * no renumbering - keep GMod entries exactly in this order and append
 * fork-only ids AFTER them.
 *
 * HL2SB-only dispatches (GMod fires these from Lua instead):
 *   309 (0x135) AddDeathNotice - GMod: cl_deathnotice.lua net.Receive ->
 *                                 hook.Run; HL2SB: hud_killfeed.cpp C++.
 *
 * Contract for consumers (see hl2sb_binmod.c for the same export rules):
 *   - declare plain `extern "C" const char *HL2SB_GetHookName( int id );`
 *     NEVER with LUA_API (gcc rejects extern "C" + extern linkage).
 *   - this file must stay pure ASCII (936 codepage build).
 */
#define LUA_LIB /* LUA_API -> dllexport on Windows, default visibility on gcc */

#include <stddef.h>
#include "lua.h"

static const char *const kHookNames[] = {
  /* 0x000 */ "AcceptInput",
  /* 0x001 */ "AdjustMouseSensitivity",
  /* 0x002 */ "AllowPlayerPickup",
  /* 0x003 */ "CalcMainActivity",
  /* 0x004 */ "CalcView",
  /* 0x005 */ "CalcViewModelView",
  /* 0x006 */ "CanExitVehicle",
  /* 0x007 */ "CanPlayerEnterVehicle",
  /* 0x008 */ "CanPlayerSuicide",
  /* 0x009 */ "ChatText",
  /* 0x00a */ "ChatTextChanged",
  /* 0x00b */ "CheckPassword",
  /* 0x00c */ "ClientSignOnStateChanged",
  /* 0x00d */ "CreateClientsideRagdoll",
  /* 0x00e */ "CreateEntityRagdoll",
  /* 0x00f */ "CreateMove",
  /* 0x010 */ "DoAnimationEvent",
  /* 0x011 */ "DoPlayerDeath",
  /* 0x012 */ "DrawMonitors",
  /* 0x013 */ "DrawPhysgunBeam",
  /* 0x014 */ "EndEntityDriving",
  /* 0x015 */ "EntityEmitSound",
  /* 0x016 */ "EntityFireBullets",
  /* 0x017 */ "PostEntityFireBullets",
  /* 0x018 */ "EntityKeyValue",
  /* 0x019 */ "EntityNetworkedVarChanged",
  /* 0x01a */ "EntityRemoved",
  /* 0x01b */ "EntityTakeDamage",
  /* 0x01c */ "PostEntityTakeDamage",
  /* 0x01d */ "FindUseEntity",
  /* 0x01e */ "FinishChat",
  /* 0x01f */ "FinishMove",
  /* 0x020 */ "GUIMouseDoublePressed",
  /* 0x021 */ "GUIMousePressed",
  /* 0x022 */ "GUIMouseReleased",
  /* 0x023 */ "GetFallDamage",
  /* 0x024 */ "GetGameDescription",
  /* 0x025 */ "GetMotionBlurValues",
  /* 0x026 */ "GetPreferredCarryAngles",
  /* 0x027 */ "GetTeamColor",
  /* 0x028 */ "GravGunOnDropped",
  /* 0x029 */ "GravGunOnPickedUp",
  /* 0x02a */ "GravGunPickupAllowed",
  /* 0x02b */ "GravGunPunt",
  /* 0x02c */ "HUDAmmoPickedUp",
  /* 0x02d */ "HUDDrawScoreBoard",
  /* 0x02e */ "HUDItemPickedUp",
  /* 0x02f */ "HUDPaint",
  /* 0x030 */ "HUDPaintBackground",
  /* 0x031 */ "DrawOverlay",
  /* 0x032 */ "CaptureVideo",
  /* 0x033 */ "HUDShouldDraw",
  /* 0x034 */ "HUDWeaponPickedUp",
  /* 0x035 */ "InitPostEntity",
  /* 0x036 */ "InputMouseApply",
  /* 0x037 */ "KeyPress",
  /* 0x038 */ "KeyRelease",
  /* 0x039 */ "Move",
  /* 0x03a */ "NeedsDepthPass",
  /* 0x03b */ "NetworkEntityCreated",
  /* 0x03c */ "NetworkIDValidated",
  /* 0x03d */ "NotifyShouldTransmit",
  /* 0x03e */ "OnAchievementAchieved",
  /* 0x03f */ "OnChatTab",
  /* 0x040 */ "OnCrazyPhysics",
  /* 0x041 */ "OnDamagedByExplosion",
  /* 0x042 */ "OnEntityCreated",
  /* 0x043 */ "OnEntityWaterLevelChanged",
  /* 0x044 */ "OnNPCKilled",
  /* 0x045 */ "OnNPCDropItem",
  /* 0x046 */ "OnPhysgunFreeze",
  /* 0x047 */ "OnPhysgunReload",
  /* 0x048 */ "OnPlayerChat",
  /* 0x049 */ "OnPlayerHitGround",
  /* 0x04a */ "PlayerChangedTeam",
  /* 0x04b */ "OnViewModelChanged",
  /* 0x04c */ "PhysgunDrop",
  /* 0x04d */ "PhysgunPickup",
  /* 0x04e */ "OnPhysgunPickup",
  /* 0x04f */ "PlayerAuthed",
  /* 0x050 */ "PlayerBindPress",
  /* 0x051 */ "PlayerButtonDown",
  /* 0x052 */ "PlayerButtonUp",
  /* 0x053 */ "PlayerCanHearPlayersVoice",
  /* 0x054 */ "PlayerCanPickupItem",
  /* 0x055 */ "PlayerCanPickupWeapon",
  /* 0x056 */ "PlayerCanSeePlayersChat",
  /* 0x057 */ "PlayerConnect",
  /* 0x058 */ "PlayerDeath",
  /* 0x059 */ "PlayerDeathSound",
  /* 0x05a */ "PlayerDeathThink",
  /* 0x05b */ "PlayerDroppedWeapon",
  /* 0x05c */ "PlayerDisconnected",
  /* 0x05d */ "PlayerDriveAnimate",
  /* 0x05e */ "PlayerEndVoice",
  /* 0x05f */ "PlayerEnteredVehicle",
  /* 0x060 */ "PlayerFootstep",
  /* 0x061 */ "PlayerHurt",
  /* 0x062 */ "PlayerInitialSpawn",
  /* 0x063 */ "PlayerLeaveVehicle",
  /* 0x064 */ "PlayerNoClip",
  /* 0x065 */ "PlayerPostThink",
  /* 0x066 */ "PlayerSay",
  /* 0x067 */ "PlayerSelectSpawn",
  /* 0x068 */ "PlayerShouldTakeDamage",
  /* 0x069 */ "PlayerShouldTaunt",
  /* 0x06a */ "PlayerSilentDeath",
  /* 0x06b */ "PlayerSpawn",
  /* 0x06c */ "PlayerSpray",
  /* 0x06d */ "PlayerStartTaunt",
  /* 0x06e */ "PlayerStartVoice",
  /* 0x06f */ "PlayerStepSoundTime",
  /* 0x070 */ "PlayerSwitchFlashlight",
  /* 0x071 */ "PlayerSwitchWeapon",
  /* 0x072 */ "PlayerTick",
  /* 0x073 */ "PlayerTraceAttack",
  /* 0x074 */ "PlayerUse",
  /* 0x075 */ "PostCleanupMap",
  /* 0x076 */ "PostDraw2DSkyBox",
  /* 0x077 */ "PostDrawEffects",
  /* 0x078 */ "PostDrawHUD",
  /* 0x079 */ "PostDrawOpaqueRenderables",
  /* 0x07a */ "PostDrawSkyBox",
  /* 0x07b */ "PostDrawTranslucentRenderables",
  /* 0x07c */ "PostDrawViewModel",
  /* 0x07d */ "PostPlayerDeath",
  /* 0x07e */ "PostPlayerDraw",
  /* 0x07f */ "PostRender",
  /* 0x080 */ "PostRenderVGUI",
  /* 0x081 */ "PreCleanupMap",
  /* 0x082 */ "PreDrawEffects",
  /* 0x083 */ "PreDrawHUD",
  /* 0x084 */ "PreDrawOpaqueRenderables",
  /* 0x085 */ "PreDrawSkyBox",
  /* 0x086 */ "PreDrawTranslucentRenderables",
  /* 0x087 */ "PreDrawViewModel",
  /* 0x088 */ "PreDrawViewModels",
  /* 0x089 */ "PrePlayerDraw",
  /* 0x08a */ "PreRender",
  /* 0x08b */ "PreventScreenClicks",
  /* 0x08c */ "PropBreak",
  /* 0x08d */ "RenderScene",
  /* 0x08e */ "RenderScreenspaceEffects",
  /* 0x08f */ "Restored",
  /* 0x090 */ "Saved",
  /* 0x091 */ "ScaleNPCDamage",
  /* 0x092 */ "ScalePlayerDamage",
  /* 0x093 */ "ScoreboardHide",
  /* 0x094 */ "ScoreboardShow",
  /* 0x095 */ "SetupMove",
  /* 0x096 */ "SetupPlayerVisibility",
  /* 0x097 */ "SetupSkyboxFog",
  /* 0x098 */ "SetupWorldFog",
  /* 0x099 */ "ShouldCollide",
  /* 0x09a */ "ShouldDrawLocalPlayer",
  /* 0x09b */ "ShowHelp",
  /* 0x09c */ "ShowSpare1",
  /* 0x09d */ "ShowSpare2",
  /* 0x09e */ "ShowTeam",
  /* 0x09f */ "ShutDown",
  /* 0x0a0 */ "SpawniconGenerated",
  /* 0x0a1 */ "StartChat",
  /* 0x0a2 */ "StartCommand",
  /* 0x0a3 */ "StartEntityDriving",
  /* 0x0a4 */ "Think",
  /* 0x0a5 */ "Tick",
  /* 0x0a6 */ "TranslateActivity",
  /* 0x0a7 */ "UpdateAnimation",
  /* 0x0a8 */ "VGUIMousePressAllowed",
  /* 0x0a9 */ "VGUIMousePressed",
  /* 0x0aa */ "VehicleMove",
  /* 0x0ab */ "ViewPunch",
  /* 0x0ac */ "WeaponEquip",
  /* 0x0ad */ "PlayerAmmoChanged",
  /* 0x0ae */ "PlayerClassChanged",
  /* 0x0af */ "PlayerHandleAnimEvent",
  /* 0x0b0 */ "PlayerFireAnimationEvent",
  /* 0x0b1 */ "OnPlayerPhysicsPickup",
  /* 0x0b2 */ "OnPlayerPhysicsDrop",
  /* 0x0b3 */ "OnPlayerJump",
  /* 0x0b4 */ "OnCloseCaptionEmit",
  /* 0x0b5 */ "HandlePlayerArmorReduction",
  /* 0x0b6 */ "OnPauseMenuShow",
  /* 0x0b7 */ "OnClientLuaError",
  /* 0x0b8 */ "OnChangeActivity",
  /* 0x0b9 */ "BehaveUpdate",
  /* 0x0ba */ "Blocked",
  /* 0x0bb */ "BodyUpdate",
  /* 0x0bc */ "Deploy",
  /* 0x0bd */ "DoImpactEffect",
  /* 0x0be */ "Draw",
  /* 0x0bf */ "DrawTranslucent",
  /* 0x0c0 */ "EndTouch",
  /* 0x0c1 */ "Equip",
  /* 0x0c2 */ "EquipAmmo",
  /* 0x0c3 */ "ExpressionFinished",
  /* 0x0c4 */ "FireAnimationEvent",
  /* 0x0c5 */ "FreezeMovement",
  /* 0x0c6 */ "GetAttackSpread",
  /* 0x0c7 */ "GetCapabilities",
  /* 0x0c8 */ "GetRelationship",
  /* 0x0c9 */ "GetRenderMesh",
  /* 0x0ca */ "HandleAnimEvent",
  /* 0x0cb */ "Holster",
  /* 0x0cc */ "ImpactTrace",
  /* 0x0cd */ "KeyValue",
  /* 0x0ce */ "OnCondition",
  /* 0x0cf */ "OnContact",
  /* 0x0d0 */ "OnIgnite",
  /* 0x0d1 */ "OnInjured",
  /* 0x0d2 */ "OnKilled",
  /* 0x0d3 */ "OnTraceAttack",
  /* 0x0d4 */ "OnLandOnGround",
  /* 0x0d5 */ "OnLeaveGround",
  /* 0x0d6 */ "OnNavAreaChanged",
  /* 0x0d7 */ "OnOtherKilled",
  /* 0x0d8 */ "OnStuck",
  /* 0x0d9 */ "OnTakeDamage",
  /* 0x0da */ "OnUnStuck",
  /* 0x0db */ "PassesDamageFilter",
  /* 0x0dc */ "PassesFilter",
  /* 0x0dd */ "PassesTriggerFilters",
  /* 0x0de */ "PhysicsCollide",
  /* 0x0df */ "PhysicsSimulate",
  /* 0x0e0 */ "PhysicsUpdate",
  /* 0x0e1 */ "RunEngineTask",
  /* 0x0e2 */ "StartEngineSchedule",
  /* 0x0e3 */ "StartEngineTask",
  /* 0x0e4 */ "StartTouch",
  /* 0x0e5 */ "TestCollision",
  /* 0x0e6 */ "Touch",
  /* 0x0e7 */ "UpdateTransmitState",
  /* 0x0e8 */ "Use",
  /* 0x0e9 */ "IsJumpLegal",
  /* 0x0ea */ "CalcWeaponProficiency",
  /* 0x0eb */ "GetShadowCastDirection",
  /* 0x0ec */ "OnEntitySight",
  /* 0x0ed */ "OnEntitySightLost",
  /* 0x0ee */ "OnMovementFailed",
  /* 0x0ef */ "OnMovementComplete",
  /* 0x0f0 */ "OnActiveWeaponChanged",
  /* 0x0f1 */ "RunAI",
  /* 0x0f2 */ "OnTaskFailed",
  /* 0x0f3 */ "OverrideMove",
  /* 0x0f4 */ "OverrideMoveFacing",
  /* 0x0f5 */ "TranslateSchedule",
  /* 0x0f6 */ "TranslateNavGoal",
  /* 0x0f7 */ "OnStateChange",
  /* 0x0f8 */ "CustomAmmoDisplay",
  /* 0x0f9 */ "ResolveCustomFlyCollision",
  /* 0x0fa */ "DrawHUD",
  /* 0x0fb */ "DrawHUDBackground",
  /* 0x0fc */ "DrawWorldModel",
  /* 0x0fd */ "DrawWorldModelTranslucent",
  /* 0x0fe */ "DrawWeaponSelection",
  /* 0x0ff */ "DoDrawCrosshair",
  /* 0x100 */ "ShouldDrawViewModel",
  /* 0x101 */ "GetTracerOrigin",
  /* 0x102 */ "OnDrop",
  /* 0x103 */ "OnRemove",
  /* 0x104 */ "PrimaryAttack",
  /* 0x105 */ "SecondaryAttack",
  /* 0x106 */ "Reload",
  /* 0x107 */ "RenderScreen",
  /* 0x108 */ "ViewModelDrawn",
  /* 0x109 */ "TranslateFOV",
  /* 0x10a */ "SetWeaponHoldType",
  /* 0x10b */ "CanBePickedUpByNPCs",
  /* 0x10c */ "NPCShoot_Primary",
  /* 0x10d */ "NPCShoot_Secondary",
  /* 0x10e */ "GetNPCRestTimes",
  /* 0x10f */ "GetNPCBurstSettings",
  /* 0x110 */ "GetNPCBulletSpread",
  /* 0x111 */ "ShouldDropOnDie",
  /* 0x112 */ "ActionSignal",
  /* 0x113 */ "AllowInput",
  /* 0x114 */ "ApplySchemeSettings",
  /* 0x115 */ "ConsoleMessage",
  /* 0x116 */ "DoClick",
  /* 0x117 */ "OnActivate",
  /* 0x118 */ "OnBeginLoadingDocument",
  /* 0x119 */ "OnCallback",
  /* 0x11a */ "OnChangeAddressBar",
  /* 0x11b */ "OnChangeTargetURL",
  /* 0x11c */ "OnChangeTitle",
  /* 0x11d */ "OnChildViewCreated",
  /* 0x11e */ "OnCursorEntered",
  /* 0x11f */ "OnCursorExited",
  /* 0x120 */ "OnCursorMoved",
  /* 0x121 */ "OnDeactivate",
  /* 0x122 */ "OnDeletion",
  /* 0x123 */ "OnDocumentReady",
  /* 0x124 */ "OnFinishLoadingDocument",
  /* 0x125 */ "OnFocusChanged",
  /* 0x126 */ "OnGetFocus",
  /* 0x127 */ "OnKeyCodePressed",
  /* 0x128 */ "OnKeyCodeReleased",
  /* 0x129 */ "OnKeyCodeTyped",
  /* 0x12a */ "OnLoseFocus",
  /* 0x12b */ "OnMousePressed",
  /* 0x12c */ "OnMouseReleased",
  /* 0x12d */ "OnMouseWheeled",
  /* 0x12e */ "OnScreenSizeChanged",
  /* 0x12f */ "OnSizeChanged",
  /* 0x130 */ "OnTextChanged",
  /* 0x131 */ "OnTextClicked",
  /* 0x132 */ "PerformLayout",
  /* 0x133 */ "ResourceLoaded",
  /* 0x134 */ "TestHover",
  /* 0x135 */ "AddDeathNotice",
};

#define HL2SB_HOOK_COUNT ( (int)( sizeof( kHookNames ) / sizeof( kHookNames[0] ) ) )

extern "C" LUA_API const char *HL2SB_GetHookName( int id )
{
  if ( id < 0 || id >= HL2SB_HOOK_COUNT ) return NULL;
  return kHookNames[id];
}

extern "C" LUA_API int HL2SB_GetHookCount( void )
{
  return HL2SB_HOOK_COUNT;
}
