#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'vscript'

def options(opt):
	return

games = {
	'hl2': ['vscript.vpc'],
	'hl2mp': ['vscript.vpc'],
	'hl1': ['vscript.vpc'],
	'episodic': ['vscript.vpc'],
	'portal': ['vscript.vpc'],
	'hl1mp': ['vscript.vpc'],
	'cstrike': ['vscript.vpc'],
	'dod': ['vscript.vpc'],
	'sourcebox': ['vscript.vpc']
}

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game
    
	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])
    
	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)
	return

def build(bld):

	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )
	includes = [
		'.\squirrel\include',
		'.\squirrel\include',
		'..\public',
		'../public/tier0',
		'../public/tier1',
		'../tier1',
		'../tier0',
	]
	libs = [
	'tier0',
	'tier1'
	]
    
	#print(game["sources"])
    
	source = game["sources"]
	includes += game["includes"]
	defines = game["defines"]
	#defines = ['VSCRIPT']
	#source.remove('../../public/bspfile.h')
	#source.remove('./notes.txt')
	#defines.remove('PROTECTED_THINGS_ENABLE')

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name	 = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use	  = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx	  = bld.get_taskgen_count()
	)
