#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vrad'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS == 'android':
		return

	source = ['vrad_launcher.cpp','stdafx.cpp']
	includes = ['../../public',
				'.',
                '../../public/tier0',
                '../../public/tier1',
                '../../common'
                ]
	defines = []
	libs = [
    'tier0',
    'tier1']

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']

	install_path = bld.env.LIBDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = 'CONSOLE,5.01',
		idx      = bld.get_taskgen_count()
	)

