#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'sourcebox'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS == 'android':
		return

	source = ['main.cpp']
	includes = ['../public']
	defines = []
	libs = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME+'_'+bld.env.DEST_OS+("_srcds" if bld.env.DEDICATED else "_launcher"),
		name     = PROJECT_NAME+'_'+bld.env.DEST_OS+("_srcds" if bld.env.DEDICATED else "_launcher"),
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

