#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'video_bink'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS not in ('linux', 'android', 'darwin', 'win32'):
		return
	if bld.env.DEST_OS == 'win32' and bld.env.DEST_CPU == 'x86':
		return

	source = [
		'bink_material.cpp',
		'bink_video.cpp',
		'yuv_rgb.c',
		'../../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
		'../'
	]

	defines = []

	libs = ['tier0','tier1','tier2','tier3','vstdlib', 'AVFORMAT', 'AVCODEC', 'SWRESAMPLE', 'AVUTIL']

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
