name: Build

on: [push, pull_request]

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
    - name: Check out source
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libbz2-dev \
          libcurl4-gnutls-dev \
          libedit-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libjpeg-dev \
          libopenal-dev \
          libpng-dev \
          libsdl2-dev \
          libswresample-dev \
          zlib1g-dev
    - name: Configure
      run: >-
        python3 ./waf configure
        -T release
        --disable-warns
        --prefix="${{ github.workspace }}/linux"
        --build-games=hl2
    - name: Build
      run: python3 ./waf build -j2
    - name: Install
      run: python3 ./waf install -j2
    - name: Save build configuration
      run: cp build/config.log linux/info.txt
    - name: Upload Linux build
      uses: actions/upload-artifact@v5
      with:
        name: source-engine-linux-x86_64
        path: linux
        if-no-files-found: error

  build-android-armv7a:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build android-armv7a
      run: |
          scripts/build-android-armv7a.sh
    - uses: actions/upload-artifact@v5
      with:
        name: build-android-armv7a
        path: /home/runner/work/source-engine-mod/android_build/lib/armeabi-v7a/*.*

  build-android-aarch64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build android-aarch64
      run: |
        scripts/build-android-arm64.sh
    - uses: actions/upload-artifact@v5
      with:
        name: build-android-aarch64
        path: /home/runner/work/source-engine-mod/android_build/lib/arm64-v8a/*.*

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v5
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --prefix=./win --disable-warns --32bits
        ./waf.bat install
    - name: Cleanup artifacts (remove .lib .pdb .obj .exp .ilk)
      run: |
        Get-ChildItem -Path ./win -Recurse -Include *.lib,*.pdb,*.obj,*.exp,*.ilk | Remove-Item -Force -Recurse
    - uses: actions/upload-artifact@v5
      with:
        name: win-source-engine-i386
        path: ./win
        if-no-files-found: error

  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v5
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --prefix=./win --disable-warns
        ./waf.bat install
    - name: Cleanup artifacts (remove .lib .pdb .obj .exp .ilk)
      run: |
        Get-ChildItem -Path ./win -Recurse -Include *.lib,*.pdb,*.obj,*.exp,*.ilk | Remove-Item -Force -Recurse
    - uses: actions/upload-artifact@v5
      with:
        name: win-source-engine-amd64
        path: ./win
        if-no-files-found: error

  build-dedicated-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v5
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release -d --prefix=./win --build-game=hl2mp -4
        ./waf.bat install
    - uses: actions/upload-artifact@v5
      with:
        name: win-source-engine-d-hl2mp
        path: ./win
        if-no-files-found: error

  build-dedicated-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v5
    - name: Build dedicated windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release -d --prefix=./win --disable-warns
        ./waf.bat install
    - name: Cleanup artifacts (remove .lib .pdb .obj .exp .ilk)
      run: |
        Get-ChildItem -Path ./win -Recurse -Include *.lib,*.pdb,*.obj,*.exp,*.ilk | Remove-Item -Force -Recurse
    - uses: actions/upload-artifact@v5
      with:
        name: win-source-engine-d-amd64
        path: ./win
        if-no-files-found: error

  build-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build macos-amd64
      run: |
        scripts/build-macos-amd64.sh
        ./waf install --prefix=./macos
    - uses: actions/upload-artifact@v5
      with:
        name: source-engine-macos-amd64
        path: ./macos
        if-no-files-found: error

  build-dedicated-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build dedicated macos-amd64
      run: |
        scripts/build-macos-amd64.sh -d
        ./waf install --prefix=./macos
    - uses: actions/upload-artifact@v5
      with:
        name: source-engine-dedicated-macos-amd64
        path: ./macos
        if-no-files-found: error
