name: Build

on: [push, pull_request]

jobs:

  build-android-aarch64:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build android-aarch64

      run: |
        scripts/build-android-arm64.sh

    - uses: actions/upload-artifact@v3
    
      with:
        
        name: build-android-aarch64

        path: /home/runner/work/source-engine-mod/android_build/lib/arm64-v8a/*.*

 