name: Build Windows hl2dm

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-hl2dm-server-win32:
    name: hl2dm Server (Win32)
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out source
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build server
        run: |
          ./waf.bat configure -T release --prefix=./win --disable-warns --enable-opus
          ./waf.bat install -j4
          cat build/config.log > ./win/info.txt

      - name: Cleanup artifacts (remove .lib .pdb .obj .exp .ilk)
        run: |
          Get-ChildItem -Path ./win -Recurse -Include *.lib,*.pdb,*.obj,*.exp,*.ilk | Remove-Item -Force -Recurse

      - name: Upload hl2dm server
        uses: actions/upload-artifact@v7
        with:
          name: hl2dm-win64
          path: ./win
          if-no-files-found: error

  build-hl2dm-win32:
    name: hl2dm Client (Win32)
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out source
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build client
        run: |
          ./waf.bat configure -T release -4 --prefix=./win --disable-warns --enable-opus
          ./waf.bat install -j4
          cat build/config.log > ./win/info.txt

      - name: Cleanup artifacts (remove .lib .pdb .obj .exp .ilk)
        run: |
          Get-ChildItem -Path ./win -Recurse -Include *.lib,*.pdb,*.obj,*.exp,*.ilk | Remove-Item -Force -Recurse

      - name: Upload hl2dm client
        uses: actions/upload-artifact@v7
        with:
          name: hl2dm-win32
          path: ./win
          if-no-files-found: error
